name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Pipenv for Github Actions
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install

      - name: Setup
        uses: VaultVulp/action-pipenv@v2.0.1
        run: |
          cp .env.example .env
          cp .pages.example .pages
          make up
          make install

      - name: Run linter
        run: |
          make lint

      - name: Build
        run: |
          make build
