name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Setup, lint, build
        run: |
          cp .env.example .env
          cp .pages.example .pages
          pipenv install
          which pylint
          pipenv run which pylint
          echo $PATH
          pipenv run echo $PATH
          export
          pipenv run pylint --rcfile=.pylintrc *.py
          pipenv run python main.py
